### ISSUE TITLE
Component : Output checker

### ISSUE THREAD

**Issue by iommu** [iommu/CSCI314Project#4]
A component that takes the input and output of @iommu 's API caller function and calculates the expected output based off of the input then compares to either pass or fail the software

**Comment by ChubbyFox** [comment]
I think it will probably be easiest and good to use the Python [unittest](https://docs.python.org/3/library/unittest.html) library to help assess the input/output. <- Leaving this comment here until I can get around to programming but anyone can add things in

**Comment by iommu** [comment]
Yes, unittest is now used in the core module used in main.py
